<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $vehicles = [
            [
                'name' => 'Toyota Land Cruiser',
                'model' => 'VXR',
                'year' => 2022,
                'type' => 'SUV',
                'description' => 'Luxury SUV with off-road capabilities.',
                'location' => 'Dubai',
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'drive_type' => '4WD',
                'seats' => 7,
                'mileage' => 15000,
                'engine' => '4.0L V6',
                'main_image_url' => 'images/vehicles/landcruiser.jpg',
                'is_for_sale' => true,
                'rental_price_day' => 400,
                'rental_price_week' => 2500,
                'rental_price_month' => 9000,
                'booking_lead_days' => 1,
                'purchase_price' => 280000,
                'deposit_amount' => 20000,
                'status' => 'available',
            ],
            [
                'name' => 'Nissan Patrol',
                'model' => 'Platinum',
                'year' => 2021,
                'type' => 'SUV',
                'description' => 'Powerful desert cruiser.',
                'location' => 'Abu Dhabi',
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'drive_type' => '4WD',
                'seats' => 8,
                'mileage' => 25000,
                'engine' => '5.6L V8',
                'main_image_url' => 'images/vehicles/patrol.jpg',
                'is_for_sale' => false,
                'rental_price_day' => 350,
                'rental_price_week' => 2200,
                'rental_price_month' => 8500,
                'booking_lead_days' => 2,
                'purchase_price' => 250000,
                'deposit_amount' => 18000,
                'status' => 'rented',
            ],
            [
                'name' => 'Ford Mustang',
                'model' => 'GT',
                'year' => 2020,
                'type' => 'Coupe',
                'description' => 'Classic American muscle car.',
                'location' => 'Dubai',
                'transmission' => 'Manual',
                'fuel_type' => 'Petrol',
                'drive_type' => 'RWD',
                'seats' => 4,
                'mileage' => 12000,
                'engine' => '5.0L V8',
                'main_image_url' => 'images/vehicles/mustang.jpg',
                'is_for_sale' => true,
                'rental_price_day' => 600,
                'rental_price_week' => 3500,
                'rental_price_month' => 12000,
                'booking_lead_days' => 1,
                'purchase_price' => 200000,
                'deposit_amount' => 15000,
                'status' => 'available',
            ],
            [
                'name' => 'Tesla Model S',
                'model' => 'Plaid',
                'year' => 2023,
                'type' => 'Sedan',
                'description' => 'High-performance electric luxury car.',
                'location' => 'Dubai',
                'transmission' => 'Automatic',
                'fuel_type' => 'Electric',
                'drive_type' => 'AWD',
                'seats' => 5,
                'mileage' => 5000,
                'engine' => 'Electric',
                'main_image_url' => 'images/vehicles/tesla.jpg',
                'is_for_sale' => true,
                'rental_price_day' => 800,
                'rental_price_week' => 5000,
                'rental_price_month' => 16000,
                'booking_lead_days' => 1,
                'purchase_price' => 450000,
                'deposit_amount' => 30000,
                'status' => 'available',
            ],
            [
                'name' => 'Mercedes G-Wagon',
                'model' => 'G63 AMG',
                'year' => 2022,
                'type' => 'SUV',
                'description' => 'Luxury off-road SUV with AMG power.',
                'location' => 'Abu Dhabi',
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'drive_type' => 'AWD',
                'seats' => 5,
                'mileage' => 10000,
                'engine' => '4.0L V8 Twin-Turbo',
                'main_image_url' => 'images/vehicles/gwagon.jpg',
                'is_for_sale' => true,
                'rental_price_day' => 1200,
                'rental_price_week' => 7000,
                'rental_price_month' => 25000,
                'booking_lead_days' => 2,
                'purchase_price' => 900000,
                'deposit_amount' => 50000,
                'status' => 'available',
            ],
            [
                'name' => 'BMW X5',
                'model' => 'xDrive40i',
                'year' => 2021,
                'type' => 'SUV',
                'description' => 'Luxury family SUV.',
                'location' => 'Sharjah',
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'drive_type' => 'AWD',
                'seats' => 5,
                'mileage' => 18000,
                'engine' => '3.0L I6 Turbo',
                'main_image_url' => 'images/vehicles/bmw-x5.jpg',
                'is_for_sale' => false,
                'rental_price_day' => 450,
                'rental_price_week' => 2800,
                'rental_price_month' => 9500,
                'booking_lead_days' => 1,
                'purchase_price' => 350000,
                'deposit_amount' => 20000,
                'status' => 'maintenance',
            ],
            [
                'name' => 'Audi A6',
                'model' => '2.0 TFSI',
                'year' => 2019,
                'type' => 'Sedan',
                'description' => 'Comfortable premium sedan.',
                'location' => 'Dubai',
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'drive_type' => 'FWD',
                'seats' => 5,
                'mileage' => 35000,
                'engine' => '2.0L Turbo',
                'main_image_url' => 'images/vehicles/audi-a6.jpg',
                'is_for_sale' => false,
                'rental_price_day' => 300,
                'rental_price_week' => 1800,
                'rental_price_month' => 6000,
                'booking_lead_days' => 1,
                'purchase_price' => 180000,
                'deposit_amount' => 10000,
                'status' => 'available',
            ],
            [
                'name' => 'Lamborghini Huracan',
                'model' => 'Evo',
                'year' => 2021,
                'type' => 'Coupe',
                'description' => 'Exotic Italian supercar.',
                'location' => 'Dubai',
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'drive_type' => 'AWD',
                'seats' => 2,
                'mileage' => 8000,
                'engine' => '5.2L V10',
                'main_image_url' => 'images/vehicles/huracan.jpg',
                'is_for_sale' => true,
                'rental_price_day' => 3000,
                'rental_price_week' => 20000,
                'rental_price_month' => 70000,
                'booking_lead_days' => 3,
                'purchase_price' => 1200000,
                'deposit_amount' => 100000,
                'status' => 'available',
            ],
            [
                'name' => 'Porsche Cayenne',
                'model' => 'Turbo',
                'year' => 2020,
                'type' => 'SUV',
                'description' => 'Luxury performance SUV.',
                'location' => 'Dubai',
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'drive_type' => 'AWD',
                'seats' => 5,
                'mileage' => 20000,
                'engine' => '4.0L V8 Turbo',
                'main_image_url' => 'images/vehicles/cayenne.jpg',
                'is_for_sale' => false,
                'rental_price_day' => 700,
                'rental_price_week' => 4500,
                'rental_price_month' => 15000,
                'booking_lead_days' => 2,
                'purchase_price' => 500000,
                'deposit_amount' => 40000,
                'status' => 'available',
            ],
            [
                'name' => 'Range Rover',
                'model' => 'Autobiography',
                'year' => 2022,
                'type' => 'SUV',
                'description' => 'Flagship luxury SUV.',
                'location' => 'Abu Dhabi',
                'transmission' => 'Automatic',
                'fuel_type' => 'Petrol',
                'drive_type' => 'AWD',
                'seats' => 5,
                'mileage' => 10000,
                'engine' => '4.4L V8',
                'main_image_url' => 'images/vehicles/rangerover.jpg',
                'is_for_sale' => true,
                'rental_price_day' => 1000,
                'rental_price_week' => 6000,
                'rental_price_month' => 20000,
                'booking_lead_days' => 2,
                'purchase_price' => 750000,
                'deposit_amount' => 50000,
                'status' => 'available',
            ],
        ];

        foreach ($vehicles as $vehicle) {
            $vehicleId = DB::table('vehicles')->insertGetId(array_merge($vehicle, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));

            // Add 2 images per vehicle
            DB::table('vehicle_images')->insert([
                [
                    'vehicle_id' => $vehicleId,
                    'url' => 'images/vehicles/gallery/' . str_replace(' ', '_', strtolower($vehicle['name'])) . '_1.jpg',
                    'sort_order' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'vehicle_id' => $vehicleId,
                    'url' => 'images/vehicles/gallery/' . str_replace(' ', '_', strtolower($vehicle['name'])) . '_2.jpg',
                    'sort_order' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }
    }
}
